models:
  - name: hub_customer
    description: > 
     This table stores unique customer records with hashed surrogate keys.
    columns:
      - name: customer_hk
        description: Hash key of customer_id, used as surrogate key.
        tests:
          - unique
          - not_null
      - name: customer_id
        description: natural key like original identifier from source.
      - name: load_dts
        description: Load timestamp.
      - name: source
        description: source of the data.

  - name: link_customer_order
    description: > 
      Link table connecting customers and orders. Uses hashed keys to track 
      relationships.
    columns:
      - name: customer_hk
        description: Foreign key references from the customer hub table.
      - name: customer_order_hk
        description: Composite hash key of customer_id and order_id.
      - name: order_hk
        description: Foreign key to the order hub.
      - name: load_dts
        description: Load timestamp.
      - name: source
        description: source of the data.

  - name: sat_customer
    description: This Satellite table storing customer descriptive data.
    columns:
      - name: customer_hk
        description: Foreign key to the customer hub.
        tests:
          - not_null
      - name: customer_email
        tests:
          - not_null
      - name: customer_name
        description: customer name
      - name: customer_email
        description: customer email
      - name: customer_phone
        description: customer phone
      - name: load_dts
        description: Load timestamp.
      - name: source
        description: source of the data.

  - name: hub
    description: Stores unique business entity
  - name: link
    description: Links customers to their orders by buisness keys.
  - name: satellite
    description: Captures descriptive attributes of customers.